workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Fix Java version in Capacitor
        script: |
          if [ -f node_modules/@capacitor/android/capacitor/build.gradle ]; then
            perl -pi -e 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' node_modules/@capacitor/android/capacitor/build.gradle
          fi
          
      - name: Build web app
        script: |
          npm run build
          
      - name: Add Android platform
        script: |
          npx cap add android || true
          npx cap sync android
          
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          
      - name: Build Android debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab